### ISSUE TITLE
gcc: fatal error: cannot specify ‘-o’ with ‘-c’, ‘-S’ or         ‘-E’ with multiple files

### ISSUE THREAD

**Issue by tiansiyuan** [NVIDIA/TransformerEngine#383]
while run:

pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable

**Comment by timmoon10** [comment]
Strange, I haven't seen this before. The two places this could happen are when building the core C++ library (handled with CMake) or the PyTorch extensions (handled with PyTorch and setuptools). Can you provide error logs so we can pin this down, as well as your CUDA, GCC, and PyTorch versions?

Alternatively, have you tried using the Docker container at https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch? It already comes with TE, so it's nifty if you want to start using it immediately.

**Comment by tiansiyuan** [comment]
Hi,

I am already in a Docker container, so that I can not use Docker in it. Am I right?

CUDA is 11.8; GCC is 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1); PyTorch is 1.12.0+cu113.

The complete outout is as below.

Thanks

$ pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable
Collecting git+https://github.com/NVIDIA/TransformerEngine.git@stable
  Cloning https://github.com/NVIDIA/TransformerEngine.git (to revision stable) to /tmp/pip-req-build-nhbczsg6
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/TransformerEngine.git /tmp/pip-req-build-nhbczsg6
  Running command git checkout -b stable --track origin/stable
  Switched to a new branch 'stable'
  Branch 'stable' set up to track remote branch 'stable' from 'origin'.
  Resolved https://github.com/NVIDIA/TransformerEngine.git to commit 3f01b4f812e0e501257278ec269499ea02b2d4f3
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Collecting pydantic (from transformer-engine==0.11.0+3f01b4f)
  Obtaining dependency information for pydantic from https://files.pythonhosted.org/packages/87/80/52770e747e4bee5012e60b2684db36c8fdf010f8dadb4ded0efec808b07d/pydantic-2.1.1-py3-none-any.whl.metadata
  Using cached pydantic-2.1.1-py3-none-any.whl.metadata (136 kB)
Requirement already satisfied: torch in /opt/conda/envs/auto/lib/python3.8/site-packages (from transformer-engine==0.11.0+3f01b4f) (1.12.0+cu113)
Collecting flash-attn>=1.0.6 (from transformer-engine==0.11.0+3f01b4f)
  Using cached flash_attn-2.0.7-cp38-cp38-linux_x86_64.whl
Collecting einops (from flash-attn>=1.0.6->transformer-engine==0.11.0+3f01b4f)
  Using cached einops-0.6.1-py3-none-any.whl (42 kB)
Requirement already satisfied: packaging in /opt/conda/envs/auto/lib/python3.8/site-packages (from flash-attn>=1.0.6->transformer-engine==0.11.0+3f01b4f) (23.1)
Requirement already satisfied: ninja in /opt/conda/envs/auto/lib/python3.8/site-packages (from flash-attn>=1.0.6->transformer-engine==0.11.0+3f01b4f) (1.11.1)
Collecting annotated-types>=0.4.0 (from pydantic->transformer-engine==0.11.0+3f01b4f)
  Obtaining dependency information for annotated-types>=0.4.0 from https://files.pythonhosted.org/packages/d8/f0/a2ee543a96cc624c35a9086f39b1ed2aa403c6d355dfe47a11ee5c64a164/annotated_types-0.5.0-py3-none-any.whl.metadata
  Using cached annotated_types-0.5.0-py3-none-any.whl.metadata (11 kB)
Collecting pydantic-core==2.4.0 (from pydantic->transformer-engine==0.11.0+3f01b4f)
  Obtaining dependency information for pydantic-core==2.4.0 from https://files.pythonhosted.org/packages/80/09/3dc9582c4ba0fa415d0a88379462f84c9352a779b27677340314425b1523/pydantic_core-2.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached pydantic_core-2.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/conda/envs/auto/lib/python3.8/site-packages (from pydantic->transformer-engine==0.11.0+3f01b4f) (4.7.1)
Using cached pydantic-2.1.1-py3-none-any.whl (370 kB)
Using cached pydantic_core-2.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.9 MB)
Using cached annotated_types-0.5.0-py3-none-any.whl (11 kB)
Building wheels for collected packages: transformer-engine
  Building wheel for transformer-engine (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [206 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/transformer_engine
      copying transformer_engine/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/paddle
      copying transformer_engine/paddle/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/paddle
      copying transformer_engine/paddle/fp8.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/paddle
      copying transformer_engine/paddle/cpp_extensions.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/paddle
      copying transformer_engine/paddle/constants.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/paddle
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/fp8.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/fused_attn.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/dot.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/softmax.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/layernorm.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/cpp_extensions.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/mlp.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      copying transformer_engine/jax/sharding.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/jit.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/fp8.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/utils.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/softmax.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/module.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/transformer.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/constants.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/tensorflow
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/common
      copying transformer_engine/common/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/common
      copying transformer_engine/common/utils.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/common
      copying transformer_engine/common/recipe.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/common
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/numerics_debug.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/jit.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/fp8.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/export.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/distributed.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/utils.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/softmax.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/te_onnx_extensions.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/attention.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/transformer.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      copying transformer_engine/pytorch/constants.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/module.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/transformer.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax/praxis
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/module.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/transformer.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/jax/flax
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/linear.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/rmsnorm.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm_mlp.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/base.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/_common.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm_linear.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/module
      creating build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/__init__.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/cast.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/gemm.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/activation.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/fused_attn.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/transpose.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/normalization.py -> build/lib.linux-x86_64-cpython-38/transformer_engine/pytorch/cpp_extensions
      running build_ext
      Building CMake extension transformer_engine
      Running command /opt/conda/bin/cmake -S /tmp/pip-req-build-nhbczsg6/transformer_engine -B /tmp/tmp0raxgf4w -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-nhbczsg6/build/lib.linux-x86_64-cpython-38 -GNinja
      CMake Error at /opt/conda/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:751 (message):
        Compiling the CUDA compiler identification source file
        "CMakeCUDACompilerId.cu" failed.
      
        Compiler: /opt/conda/bin/nvcc
      
        Build flags:
      
        Id flags: --keep;--keep-dir;tmp -v
      
      
      
        The output was:
      
        1
      
        #$ _NVVM_BRANCH_=nvvm
      
        #$ _SPACE_=
      
        #$ _CUDART_=cudart
      
        #$ _HERE_=/opt/conda/bin
      
        #$ _THERE_=/opt/conda/bin
      
        #$ _TARGET_SIZE_=
      
        #$ _TARGET_DIR_=
      
        #$ _TARGET_SIZE_=64
      
        #$ TOP=/opt/conda/bin/..
      
        #$ NVVMIR_LIBRARY_DIR=/opt/conda/bin/../nvvm/libdevice
      
        #$ LD_LIBRARY_PATH=/opt/conda/bin/../lib:
      
        #$
        PATH=/opt/conda/bin/../nvvm/bin:/opt/conda/bin:/opt/conda/envs/auto/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      
      
        #$ INCLUDES="-I/opt/conda/bin/../include"
        /usr/local/cuda-11.8/targets/x86_64-linux/include
      
        #$ LIBRARIES= "-L/opt/conda/bin/../lib/stubs" "-L/opt/conda/bin/../lib"
      
        #$ CUDAFE_FLAGS=
      
        #$ PTXAS_FLAGS=
      
        #$ rm tmp/a_dlink.reg.c
      
        #$ gcc -D__CUDA_ARCH_LIST__=520 -E -x c++ -D__CUDACC__ -D__NVCC__
        "-I/opt/conda/bin/../include"
        /usr/local/cuda-11.8/targets/x86_64-linux/include -D__CUDACC_VER_MAJOR__=12
        -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=66
        -D__CUDA_API_VER_MAJOR__=12 -D__CUDA_API_VER_MINOR__=1
        -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include "cuda_runtime.h" -m64
        "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp4.ii"
      
        gcc: fatal error: cannot specify ‘-o’ with ‘-c’, ‘-S’ or
        ‘-E’ with multiple files
      
        compilation terminated.
      
        # --error 0x1 --
      
      
      
      
      
      Call Stack (most recent call first):
        /opt/conda/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
        /opt/conda/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
        /opt/conda/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
        CMakeLists.txt:15 (project)
      
      
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-req-build-nhbczsg6/setup.py", line 364, in _build_cmake
          subprocess.run(command, cwd=build_dir, check=True)
        File "/opt/conda/envs/auto/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['/opt/conda/bin/cmake', '-S', '/tmp/pip-req-build-nhbczsg6/transformer_engine', '-B', '/tmp/tmp0raxgf4w', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-nhbczsg6/build/lib.linux-x86_64-cpython-38', '-GNinja']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-nhbczsg6/setup.py", line 637, in <module>
          main()
        File "/tmp/pip-req-build-nhbczsg6/setup.py", line 622, in main
          setuptools.setup(
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 349, in run
          self.run_command("build")
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/opt/conda/envs/auto/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-nhbczsg6/setup.py", line 394, in run
          ext._build_cmake(
        File "/tmp/pip-req-build-nhbczsg6/setup.py", line 366, in _build_cmake
          raise RuntimeError(f"Error when running CMake: {e}")
      RuntimeError: Error when running CMake: Command '['/opt/conda/bin/cmake', '-S', '/tmp/pip-req-build-nhbczsg6/transformer_engine', '-B', '/tmp/tmp0raxgf4w', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-nhbczsg6/build/lib.linux-x86_64-cpython-38', '-GNinja']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for transformer-engine
  Running setup.py clean for transformer-engine
Failed to build transformer-engine
ERROR: Could not build wheels for transformer-engine, which is required to install pyproject.toml-based projects

**Comment by ksivaman** [comment]
Could you please upgrade your setup, specifically PyTorch? There are some python level features we use that require `torch>=1.13` but also FA version `2.0.7` (>2) which you are using also has had multiple build issues with older PyTorch versions.

**Comment by timmoon10** [comment]
This is failing very early, right as CMake is trying to detect the CUDA and C++ compilers:

https://github.com/NVIDIA/TransformerEngine/blob/e4f9e7673b3b06d303164943f4ca33f46e865437/transformer_engine/CMakeLists.txt#L15

It seems to be a compiler configuration issue. It finds nvcc at `/opt/conda/bin/nvcc`, so that seems fine. I wonder if it's picking up the wrong GCC? You have GCC 9.4.0, but perhaps your system GCC is taking precedence and that could be something ancient. Try setting the environment variable `CXX` to your desired GCC path.

**Comment by tiansiyuan** [comment]
$ /opt/conda/bin/nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

$CUDA_HOME/bin/nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by tiansiyuan** [comment]
Before 

export INCLUDES=/usr/local/cuda-11.8/targets/x86_64-linux/include

the error is:

cc1plus: fatal error: cuda_runtime.h: No such file or directory

And the complete output is:

Collecting git+https://github.com/NVIDIA/TransformerEngine.git@stable
  Cloning https://github.com/NVIDIA/TransformerEngine.git (to revision stable) to /tmp/pip-req-build-73xo53vh
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/TransformerEngine.git /tmp/pip-req-build-73xo53vh
  Running command git checkout -b stable --track origin/stable
  Switched to a new branch 'stable'
  Branch 'stable' set up to track remote branch 'stable' from 'origin'.
  Resolved https://github.com/NVIDIA/TransformerEngine.git to commit 3f01b4f812e0e501257278ec269499ea02b2d4f3
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pydantic in /opt/conda/lib/python3.10/site-packages (from transformer-engine==0.11.0+3f01b4f) (1.10.12)
Requirement already satisfied: torch in /opt/conda/lib/python3.10/site-packages (from transformer-engine==0.11.0+3f01b4f) (2.0.1)
Requirement already satisfied: flash-attn>=1.0.6 in /opt/conda/lib/python3.10/site-packages (from transformer-engine==0.11.0+3f01b4f) (2.0.7)
Requirement already satisfied: tensorflow in /opt/conda/lib/python3.10/site-packages (from transformer-engine==0.11.0+3f01b4f) (2.10.1)
Requirement already satisfied: einops in /opt/conda/lib/python3.10/site-packages (from flash-attn>=1.0.6->transformer-engine==0.11.0+3f01b4f) (0.6.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from flash-attn>=1.0.6->transformer-engine==0.11.0+3f01b4f) (23.0)
Requirement already satisfied: ninja in /opt/conda/lib/python3.10/site-packages (from flash-attn>=1.0.6->transformer-engine==0.11.0+3f01b4f) (1.11.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/conda/lib/python3.10/site-packages (from pydantic->transformer-engine==0.11.0+3f01b4f) (4.5.0)
Requirement already satisfied: absl-py>=1.0.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (23.3.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (1.53.0)
Requirement already satisfied: h5py>=2.9.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (3.8.0)
Requirement already satisfied: keras<2.11,>=2.10.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (2.10.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (1.1.2)
Requirement already satisfied: libclang>=13.0.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (16.0.0)
Requirement already satisfied: numpy>=1.20 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (1.25.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (3.3.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (3.19.6)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (68.1.0)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (1.16.0)
Requirement already satisfied: tensorboard<2.11,>=2.10 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (2.10.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (0.32.0)
Requirement already satisfied: tensorflow-estimator<2.11,>=2.10.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (2.10.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (2.2.0)
Requirement already satisfied: wrapt>=1.11.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow->transformer-engine==0.11.0+3f01b4f) (1.15.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (3.12.2)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (1.11.1)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (3.0)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (11.7.91)
Requirement already satisfied: triton==2.0.0 in /opt/conda/lib/python3.10/site-packages (from torch->transformer-engine==0.11.0+3f01b4f) (2.0.0)
Requirement already satisfied: wheel in /opt/conda/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->transformer-engine==0.11.0+3f01b4f) (0.41.1)
Requirement already satisfied: cmake in /opt/conda/lib/python3.10/site-packages (from triton==2.0.0->torch->transformer-engine==0.11.0+3f01b4f) (3.27.2)
Requirement already satisfied: lit in /opt/conda/lib/python3.10/site-packages (from triton==2.0.0->torch->transformer-engine==0.11.0+3f01b4f) (16.0.6)
Requirement already satisfied: google-auth<3,>=1.6.3 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (2.17.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (3.4.3)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (2.28.2)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (2.2.3)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch->transformer-engine==0.11.0+3f01b4f) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch->transformer-engine==0.11.0+3f01b4f) (1.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (2022.12.7)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow->transformer-engine==0.11.0+3f01b4f) (3.2.2)
Building wheels for collected packages: transformer-engine
  Building wheel for transformer-engine (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [220 lines of output]
      2023-08-18 00:18:45.006153: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
      To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
      2023-08-18 00:18:45.119596: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
      2023-08-18 00:18:45.149399: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
      2023-08-18 00:18:45.653486: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
      2023-08-18 00:18:45.653536: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
      2023-08-18 00:18:45.653542: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
      /opt/conda/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/transformer_engine
      copying transformer_engine/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
      copying transformer_engine/paddle/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
      copying transformer_engine/paddle/fp8.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
      copying transformer_engine/paddle/cpp_extensions.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
      copying transformer_engine/paddle/constants.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/fp8.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/fused_attn.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/dot.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/softmax.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/layernorm.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/cpp_extensions.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/mlp.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      copying transformer_engine/jax/sharding.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/jit.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/fp8.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/utils.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/softmax.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/module.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/transformer.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/constants.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/tensorflow
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/common
      copying transformer_engine/common/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/common
      copying transformer_engine/common/utils.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/common
      copying transformer_engine/common/recipe.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/common
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/numerics_debug.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/jit.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/fp8.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/export.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/distributed.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/utils.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/softmax.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/te_onnx_extensions.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/attention.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/transformer.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      copying transformer_engine/pytorch/constants.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/module.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/transformer.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax/praxis
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/module.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/transformer.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax/flax
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/linear.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/rmsnorm.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm_mlp.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/base.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/_common.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm_linear.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/module
      creating build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/cast.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/gemm.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/activation.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/fused_attn.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/transpose.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/normalization.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch/cpp_extensions
      running build_ext
      Building CMake extension transformer_engine
      Running command /opt/conda/lib/python3.10/site-packages/cmake/data/bin/cmake -S /tmp/pip-req-build-73xo53vh/transformer_engine -B /tmp/tmpgep92ydw -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-73xo53vh/build/lib.linux-x86_64-cpython-310 -DENABLE_TENSORFLOW=ON -GNinja -Dpybind11_DIR=/tmp/pip-req-build-73xo53vh/.eggs/pybind11-2.11.1-py3.10.egg/pybind11/share/cmake/pybind11
      CMake Error at /opt/conda/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:756 (message):
        Compiling the CUDA compiler identification source file
        "CMakeCUDACompilerId.cu" failed.
      
        Compiler: /opt/conda/bin/nvcc
      
        Build flags:
      
        Id flags: --keep;--keep-dir;tmp -v
      
      
      
        The output was:
      
        1
      
        #$ _NVVM_BRANCH_=nvvm
      
        #$ _SPACE_=
      
        #$ _CUDART_=cudart
      
        #$ _HERE_=/opt/conda/bin
      
        #$ _THERE_=/opt/conda/bin
      
        #$ _TARGET_SIZE_=
      
        #$ _TARGET_DIR_=
      
        #$ _TARGET_SIZE_=64
      
        #$ TOP=/opt/conda/bin/..
      
        #$ NVVMIR_LIBRARY_DIR=/opt/conda/bin/../nvvm/libdevice
      
        #$ LD_LIBRARY_PATH=/opt/conda/bin/../lib:
      
        #$
        PATH=/opt/conda/bin/../nvvm/bin:/opt/conda/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      
      
        #$ INCLUDES="-I/opt/conda/bin/../include"
      
        #$ LIBRARIES= "-L/opt/conda/bin/../lib/stubs" "-L/opt/conda/bin/../lib"
      
        #$ CUDAFE_FLAGS=
      
        #$ PTXAS_FLAGS=
      
        #$ rm tmp/a_dlink.reg.c
      
        #$ gcc -D__CUDA_ARCH_LIST__=520 -E -x c++ -D__CUDACC__ -D__NVCC__
        "-I/opt/conda/bin/../include" -D__CUDACC_VER_MAJOR__=12
        -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=66
        -D__CUDA_API_VER_MAJOR__=12 -D__CUDA_API_VER_MINOR__=1
        -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include "cuda_runtime.h" -m64
        "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp4.ii"
      
        cc1plus: fatal error: cuda_runtime.h: No such file or directory
      
        compilation terminated.
      
        # --error 0x1 --
      
      
      
      
      
      Call Stack (most recent call first):
        /opt/conda/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
        /opt/conda/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
        /opt/conda/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
        CMakeLists.txt:15 (project)
      
      
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-req-build-73xo53vh/setup.py", line 364, in _build_cmake
          subprocess.run(command, cwd=build_dir, check=True)
        File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['/opt/conda/lib/python3.10/site-packages/cmake/data/bin/cmake', '-S', '/tmp/pip-req-build-73xo53vh/transformer_engine', '-B', '/tmp/tmpgep92ydw', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-73xo53vh/build/lib.linux-x86_64-cpython-310', '-DENABLE_TENSORFLOW=ON', '-GNinja', '-Dpybind11_DIR=/tmp/pip-req-build-73xo53vh/.eggs/pybind11-2.11.1-py3.10.egg/pybind11/share/cmake/pybind11']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-73xo53vh/setup.py", line 637, in <module>
          main()
        File "/tmp/pip-req-build-73xo53vh/setup.py", line 622, in main
          setuptools.setup(
        File "/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 349, in run
          self.run_command("build")
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-73xo53vh/setup.py", line 394, in run
          ext._build_cmake(
        File "/tmp/pip-req-build-73xo53vh/setup.py", line 366, in _build_cmake
          raise RuntimeError(f"Error when running CMake: {e}")
      RuntimeError: Error when running CMake: Command '['/opt/conda/lib/python3.10/site-packages/cmake/data/bin/cmake', '-S', '/tmp/pip-req-build-73xo53vh/transformer_engine', '-B', '/tmp/tmpgep92ydw', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-73xo53vh/build/lib.linux-x86_64-cpython-310', '-DENABLE_TENSORFLOW=ON', '-GNinja', '-Dpybind11_DIR=/tmp/pip-req-build-73xo53vh/.eggs/pybind11-2.11.1-py3.10.egg/pybind11/share/cmake/pybind11']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for transformer-engine
  Running setup.py clean for transformer-engine
Failed to build transformer-engine
ERROR: Could not build wheels for transformer-engine, which is required to install pyproject.toml-based projects

**Comment by timmoon10** [comment]
These errors are happening within CMake's basic checks for compiler support, so it still looks like a compiler configuration error. Let's try a test without Transformer Engine at all. Make a `CMakeLists.txt` file:
```
cmake_minimum_required(VERSION 3.18)
project(myproject LANGUAGES CUDA CXX)
```
Then call `cmake .` in the directory.

My current guess is that CMake is detecting an old version of GCC. This can be fixed by adding the correct GCC to your path or setting `CXX=/path/to/g++` in your environment.

If the simple CMake project works, then the most likely culprits are related the C++17 support or Lovelace/Hopper support:
https://github.com/NVIDIA/TransformerEngine/blob/e4f9e7673b3b06d303164943f4ca33f46e865437/transformer_engine/CMakeLists.txt#L7-L13

**Comment by tiansiyuan** [comment]
export CXX=/usr/bin/g++ 

Does not make any difference. 

cmake . with the simple CmakeLists.txt file produces the same error messages.

**Comment by sam-h-bean** [comment]
This is still happening @timmoon10. Not sure why we closed this. I get the same issue building from Ray docker image for Cuda 12.2. I can run everything including deepspeed but not with transformer engine
